ONSJobTracker/ONSJobTracker/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ONSJobTracker.CustomizedFunction;
using ONSJobTracker.Models;
using ONSJobTracker.ViewModels.MenuDetails;

namespace ONSJobTracker.Controllers
{
    [SessionCheck]
    public class UserMenuController : Controller
    {
        #region Master Menu

        public async Task<ActionResult> MenuMasterIndex()
        {
            using (var db = new xOssContext())
            {
                ViewBag.allmastermenu = db.MenuMaster.OrderBy(x => x.ModuleSl).ToList();
                return await Task.Run(() => View());
            }
        }
        [HttpPost]
        public async Task<ActionResult> CreateMenuMaster(MenuMaster model)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    if (model.Action == "Save")
                    {
                        if (db.MenuMaster.Any(o => o.ModuleName.ToLower() == model.ModuleName.ToLower()))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Master Menu already exists.";
                        }
                        else
                        {
                            model.AddReady(true, DateTime.Now);
                            db.MenuMaster.Add(model);
                            await db.SaveChangesAsync();

                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Insert Successfully.";
                        }
                    }
                    else if (model.Action == "Update")
                    {
                        if (db.MenuMaster.Any(x => x.ModuleName == model.ModuleName && x.Id != model.Id))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Master Menu already exists.";
                        }
                        else
                        {
                            MenuMaster selectSingle = db.MenuMaster.FirstOrDefault(x => x.Id == model.Id);
                            // to remove  same key already exists in the ObjectStateManager
                            ((IObjectContextAdapter)db).ObjectContext.Detach(selectSingle);
                            if (selectSingle != null)
                            {

                                model.InsertBy = selectSingle.InsertBy;
                                model.InsertDate = selectSingle.InsertDate;

                                model.UpdateReady(true, DateTime.Now);
                                SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "MenuMaster", "Update");
                                db.Entry(model).State = EntityState.Modified;
                                await db.SaveChangesAsync();
                                //sweet alert
                                Session["success_div"] = "true";
                                Session["success_msg"] = "Updated Successfully.";
                            }
                        }

                    }
                }
                return RedirectToAction("MenuMasterIndex");
            }
            catch (Exception e)
            {

                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return await Task.Run(() => View("MenuMasterIndex"));
        }

        public async Task<ActionResult> DeleteMenuMaster(int id)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    MenuMaster selectSingle = db.MenuMaster.Find(id);
                    if (selectSingle != null)
                    {
                        db.MenuMaster.Remove(selectSingle);
                        SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "MenuMaster", "Delete");
                        await db.SaveChangesAsync();
                        //sweet alert
                        Session["success_div"] = "true";
                        Session["success_msg"] = "Delete Successfully.";
                        return RedirectToAction("MenuMasterIndex");
                    }
                }
            }
            catch (Exception e)
            {

                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return RedirectToAction("MenuMasterIndex");
        }


        #endregion

        #region Details Menu

        public async Task<ActionResult> MenuDetailsIndex()
        {
            ViewBag.allmastermenu= new SelectList(DropDownListHelper.GetMasterMenu(), "Value", "Text");
            ViewBag.allmenutype= new SelectList(DropDownListHelper.GetMenuTypes(), "Value", "Text");
            MenuDetailsViewModel model = new MenuDetailsViewModel();
            ViewBag.allmenudetails = model.GetAllUserMenuDetails();
            return await Task.Run(() => View());
        }
        [HttpPost]
        public async Task<ActionResult> CreateMenuDetails(MenuDetails model)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    if (model.Action == "Save")
                    {
                        if (db.MenuDetails.Any(o => o.MenuName.ToLower() == model.MenuName.ToLower()))
                        {
                            //sweet alert
                            Session["warning_div"] = "true";
                            Session["warning_msg"] = "Details Menu already exists.";
                        }
                        else
                        {
                            model.AddReady(true, DateTime.Now);
                            db.MenuDetails.Add(model);
                            db.SaveChanges();
                            UserManager manager=new UserManager();
                            manager.AssignRoleForMenuDetails(model.Id,model.MenuMasterFk);
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Insert Successfully.";
                        }
                    }
                    else if (model.Action == "Update")
                    {
                        if (db.MenuDetails.Any(x => x.MenuName == model.MenuName && x.Id != model.Id))
                        {
                            //sweet alert
                            Session["warning_div"] = "true";
                            Session["warning_msg"] = "Details Menu already exists.";
                        }
                        else
                        {
                            MenuDetails selectSingle = db.MenuDetails.FirstOrDefault(x => x.Id == model.Id);
                            // to remove  same key already exists in the ObjectStateManager
                            ((IObjectContextAdapter)db).ObjectContext.Detach(selectSingle);
                            if (selectSingle != null)
                            {

                                model.InsertBy = selectSingle.InsertBy;
                                model.InsertDate = selectSingle.InsertDate;

                                model.UpdateReady(true, DateTime.Now);
                                SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "MenuDetails", "Update");
                                db.Entry(model).State = EntityState.Modified;
                                await db.SaveChangesAsync();
                                //sweet alert
                                Session["success_div"] = "true";
                                Session["success_msg"] = "Updated Successfully.";
                            }
                        }

                    }
                }
                return RedirectToAction("MenuDetailsIndex");
            }
            catch (Exception e)
            {

                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return await Task.Run(() => View("MenuMasterIndex"));
        }

        public ActionResult DeleteMenuDetails(int id)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    MenuDetails selectSingle = db.MenuDetails.Find(id);
                    if (selectSingle != null)
                    {
                        db.MenuDetails.Remove(selectSingle);
                        SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "MenuDetails", "Delete");
                        db.SaveChanges();
                        UserManager manager=new UserManager();
                        manager.DeleteAssignedRoleForMenuDetails(id);
                        //sweet alert
                        Session["success_div"] = "true";
                        Session["success_msg"] = "Delete Successfully.";
                        return RedirectToAction("MenuDetailsIndex");
                    }
                }
            }
            catch (Exception e)
            {

ONSJobTracker/ONSJobTracker/Views/UserMenu/MenuDetailsIndex.cshtml
@using ONSJobTracker.Models
@model MenuDetails
@using ONSJobTracker.ViewModels.MenuDetails;
@{
    ViewBag.Title = "Master Details Index";
    var tdmodulename = "tdmodulename";
    var tdmoduleId = "tdmoduleId";
    var tdmenuname = "tdmenuname";
    var tdmenutypeid = "tdmenutypeid";
    var tdcontrollername = "tdcontrollername";
    var tdactionname = "tdactionname";
    var tdismenu = "tdismenu";
    var tdsl = "tdsl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- form start -->
@using (Html.BeginForm("CreateMenuDetails", "UserMenu", FormMethod.Post, new { id = "menudetails" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id, new { Value = "", id = "hidId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Details Menu
            <small>Setting</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">DetailsMenuIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Details Menu</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuMasterFk) &nbsp;<i class="ion-star"></i>
                            @Html.DropDownListFor(model => model.MenuMasterFk, ViewBag.allmastermenu as SelectList, "---Select Master Menu---", new {id = "ddlMasterMenu", @class = "form-control select2", style = "width:100%"})
                            @Html.ValidationMessageFor(model => model.MenuMasterFk, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuType)&nbsp;<i class="ion-star"></i>
                            @Html.DropDownListFor(model => model.MenuType, ViewBag.allmenutype as SelectList, "---Select Menu Type---", new { id = "ddlMenuType", @class = "form-control select2", style = "width:100%" })
                            @Html.ValidationMessageFor(model => model.MenuType, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuName)&nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.MenuName, new { id = "txtMenuName", placeholder = "Menu Name", @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MenuSl)&nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.MenuSl, new { id = "txtMenuSl", placeholder = "Menu Sl", @class = "form-control", style = "width:100%;",type= "number" })
                            @Html.ValidationMessageFor(model => model.MenuSl, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ControllerName)&nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.ControllerName, new { id = "txtControllerName", placeholder = "Controller Name", @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.ControllerName, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ActionName)&nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.ActionName, new { id = "txtActionName", placeholder = "Action Name", @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.ActionName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <div class="checkbox icheck">
                                <label>
                                    @Html.CheckBoxFor(model=>model.IsMenu,new {id="chkismenu"})&nbsp;&nbsp; <span style="font-weight: bold;font-size: 16px">Is Menu</span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                        <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Details Menu</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="tablewithsearch" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden">Id</th>
                                    <th style="width: 5%">#</th>
                                    <th style="width: 15%">Module Name</th>
                                    <th class="hidden">Module Id</th>
                                    <th style="width: 15%">Menu Name</th>
                                    <th style="width: 15%">Menu Type</th>
                                    <th class="hidden">Menu Type Id</th>
                                    <th style="width: 15%">Controller Name</th>
                                    <th style="width: 15%">Action Name</th>
                                    <th style="width: 15%">Is Menu</th>
                                    <th style="width: 15%">Menu Sl</th>
                                    <th style="width: 15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    List<MenuDetailsViewModel> detailsmenus = ViewBag.allmenudetails as List<MenuDetailsViewModel>;
                                    int sl = 0;
                                    if (detailsmenus != null)
                                    {

                                        foreach (var menu in detailsmenus)
                                        {
                                            sl += 1;
                                            <tr>
                                                <td class="hidden">@menu.Id</td>
                                                <td>@sl</td>
                                                <td id="@tdmodulename@menu.Id">@menu.ModuleName</td>
                                                <td class="hidden" id="@tdmoduleId@menu.Id">@menu.ModuleId</td>
                                                <td id="@tdmenuname@menu.Id">@menu.MenuName</td>
                                                <td>@menu.MenuType</td>
                                                <td class="hidden" id="@tdmenutypeid@menu.Id">@menu.MenuType</td>
                                                <td id="@tdcontrollername@menu.Id">@menu.ControllerName</td>
                                                <td id="@tdactionname@menu.Id">@menu.ActionName</td>
                                                <td id="@tdismenu@menu.Id">@menu.IsMenu</td>
                                                <td id="@tdsl@menu.Id">@menu.MenuSl</td>
                                                <td style="text-align: center;cursor: pointer">
                                                    <a id="@menu.Id" onclick=" menuinfo(this);" title="Edit"
                                                       data-placement="top">
                                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                    </a>
                                                    <a href="@Url.Action("DeleteMenuDetails", "UserMenu", new RouteValueDictionary(new {id = menu.Id}))" id="@menu.Id" class="glyphicon glyphicon-trash no-print"
                                                       data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                       data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Details Menu Deleting"
                                                       data-swal-text="Are you sure to Delete this Details Menu">
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
                                    }


@section ScriptFile {

    <script type="text/javascript">
        function menuinfo(elem) {
            if (elem !== null) {
                var r = elem.id;
                
                $('#hidId').val(r);
                $('#hidAction').val('Update');
                $('#btnsave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#ddlMasterMenu').val($('#tdmoduleId' + r).text().trim()).trigger('change');
                $('#ddlMenuType').val($('#tdmenutypeid' + r).text().trim()).trigger('change');
                $('#txtMenuName').val($('#tdmenuname' + r).text().trim());
                $('#txtMenuSl').val($('#tdsl' + r).text().trim());
                $('#txtControllerName').val($('#tdcontrollername' + r).text().trim());
                $('#txtActionName').val($('#tdactionname' + r).text().trim());
                var c = ($('#tdismenu' + r)).text().trim();
                if (c==='True') {
                    $('#chkismenu').iCheck('check');
                } else {
                    $('#chkismenu').iCheck('uncheck');
                }
                

            }
        }
        $(document).off("click", "#btnreset");
        $(document).on("click", "#btnreset", function (e) {
            e.preventDefault();
            var act = $('#hidAction').val();
            if (act === "Update") {
                $('#hidAction').val("Save");
                $('#hidId').val('');
                $('#btnsave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");
                $('#ddlMasterMenu').val("").trigger('change');
                $('#ddlMenuType').val("").trigger('change');
                $('#txtMenuName').val("");
                $('#txtMenuSl').val("");
                $('#txtControllerName').val("");
                $('#txtActionName').val("");
                $('#chkismenu').iCheck('uncheck');
            } 
        });
    </script>

}

ONSJobTracker/ONSJobTracker/Views/UserMenu/MenuMasterIndex.cshtml
@using ONSJobTracker.Models
@model MenuMaster
@{
    ViewBag.Title = "Master Menu Index";
    var tdname = "tdname";
    var tdsl = "tdsl";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- form start -->
@using (Html.BeginForm("CreateMenuMaster", "UserMenu", FormMethod.Post, new { id = "menumaster" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id, new { Value = "", id = "hidId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Master Menu
            <small>Setting</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">MasterMenuIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Master Menu</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ModuleName) &nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.ModuleName, new { id = "txtModuleName", placeholder = "Module Name", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ModuleName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ModuleSl)
                            @Html.TextBoxFor(model => model.ModuleSl, new { id = "txtModuleSl", placeholder = "Module Sl", @class = "form-control", style = "width:100%;",type= "number" })
                            @Html.ValidationMessageFor(model => model.ModuleSl, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                        <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Master Menu</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="tablewithsearch" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden">Id</th>
                                    <th style="width: 10%">#</th>
                                    <th style="width: 30%">Name</th>
                                    <th style="width: 50%">Serial</th>
                                    <th style="width: 10%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    List<MenuMaster> mastermenus = ViewBag.allmastermenu as List<MenuMaster>;
                                    int sl = 0;
                                    if (mastermenus != null)
                                    {

                                        foreach (var menu in mastermenus)
                                        {
                                            sl += 1;
                                            <tr>
                                                <td class="hidden">@menu.Id</td>
                                                <td>@sl</td>
                                                <td id="@tdname@menu.Id">@menu.ModuleName</td>
                                                <td id="@tdsl@menu.Id">@menu.ModuleSl</td>
                                                <td style="text-align: center;cursor: pointer">
                                                    <a id="@menu.Id" onclick=" menuinfo(this);" title="Edit"
                                                       data-placement="top">
                                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                    </a>
                                                    <a href="@Url.Action("DeleteMenuMaster", "UserMenu", new RouteValueDictionary(new {id = menu.Id}))" id="@menu.Id" class="glyphicon glyphicon-trash no-print"
                                                       data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                       data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Master Menu Deleting"
                                                       data-swal-text="Are you sure to Delete this Master Menu">
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
                                    }

@section ScriptFile {
    <script type="text/javascript">
        function menuinfo(elem) {
            if (elem !== null) {
                var r = elem.id;
                $('#hidId').val(r);
                $('#hidAction').val('Update');
                $('#btnsave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#txtModuleName').val($('#tdname' + r).text().trim());
                $('#txtModuleSl').val($('#tdsl' + r).text().trim());

            }
        }
        $(document).off("click", "#btnreset");
        $(document).on("click", "#btnreset", function (e) {
            e.preventDefault();
            var act = $('#hidAction').val();
            if (act === "Update") {
                $('#hidAction').val("Save");
                $('#hidId').val('');
                $('#btnsave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");
                $('#txtModuleName').val("");
                $('#txtModuleSl').val("");
            } else {

            }
        });
    </script>

}