ONSJobTracker/ONSJobTracker/Models/Status.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ONSJobTracker.Models
{
    public class WorkDeliveryStatus: BaseModel
    {
        [NotMapped]
        [DisplayName("Project")]
        public Int64 ProjectFk { get; set; } //Po Master Id

        [DisplayName("PO.")]
        public Int64 PoFk { get; set; } //Po Master Id

        [DisplayName("Site")]
        public Int64 SiteFk { get; set; }  // Po Details Id....
        [DisplayName("Site Name")]
        [NotMapped]
        public string SiteName { get; set; }
        
        [DisplayName("Field Engineer")]
        public Int64 FieldEngineerFk { get; set; }
        [DisplayName("Report Engineer")]
        public Int64 ReportEngineerFk { get; set; }
        [DisplayName("Work Status")]
        public Int64 WorkStatusFk { get; set; }
        [DisplayName("Report Status")]
        public Int64 ReportStatusFk { get; set; }
        [DisplayName("Completed Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime CompletedDate { get; set; }
        [DisplayName("Delivered Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime? DeliveredDate { get; set; }
        //[DisplayName("PAC Status")]
        //public Int64 PacStatusFk { get; set; }
        //[DisplayName("FAC Status")]
        //public Int64 FacStatusFk { get; set; }
        [DisplayName("Remarks")]
        [StringLength(200)]
        public string Remarks { get; set; }

        [NotMapped]
        public bool IsReportReassign { get; set; }
        [NotMapped]
        public bool IsWorkReassign { get; set; }
        [NotMapped]
        public Int64 ReportWorkRef { get; set; }
    }

    public class AcceptanceStatus : BaseModel
    {
        [DisplayName("Project")]
        [NotMapped]
        public Int64 ProjectFk { get; set; }
        [DisplayName("PO.")]
        public Int64 PoFk { get; set; }
        [DisplayName("Site Name")]
        public Int64 SiteFk { get; set; }  // Po Details Id....
        [NotMapped]
        [DisplayName("Client Name")]
        public string ClientName { get; set; }
        [NotMapped]
        public string Po { get; set; }
        //[DisplayName("PAC")]
        //public Int64 PacStatusFk { get; set; }
        //[DisplayName("FAC")]
        //public Int64 FacStatusFk { get; set; }
        [NotMapped]
        [DisplayName("Acceptance Status")]
        public List<string> Statuses { get; set; }
        [StringLength(200)]
        public string Remarks { get; set; }
    }
    public class ReportEngineerWorkStatus : BaseModel
    {
        [DisplayName("Project")]
        [NotMapped]
        public Int64 ProjectFk { get; set; }
        [DisplayName("PO")]
        public Int64 PoFk { get; set; }  // Po Master Id
        [DisplayName("Site")]
        public Int64 SiteFk { get; set; }  // Po Details Id
        public Int64 PlanningMasterFk { get; set; }
        public string ReportFile { get; set; }
        [DisplayName("Work Status")]
        public Int64 WorkStatusFk { get; set; }
        [DisplayName("Report Status")]
        public Int64 ReportStatusFk { get; set; }
        [DisplayName("Completed Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime? CompletedDate { get; set; }
        [DisplayName("Delivered Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime DeliveredDate { get; set; }
        [NotMapped]
        public string SiteName { get; set; }
        public bool IsReportReassign { get; set; }
        public bool IsWorkReassign { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsReadyForAcceptance { get; set; }
        
        public Int64 ReportWorkRef { get; set; }
        public string Remarks { get; set; }
        public ReportEngineerWorkStatus()
        {
            IsReportReassign = false;
            IsWorkReassign = false;
            IsDelivered = true;
            ReportWorkRef = 0;
            IsReadyForAcceptance = false;
        }
    }
    public class InvoiceMaster : BaseModel
    {
        [DisplayName("Inv. Status")]
        public Int64 InvoiceStatusFk { get; set; }
        [DisplayName("Proj. Payment Date")]
        public DateTime ProjectedPaymentDate { get; set; }
        [DisplayName("Inv. Sub. Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [DataType(DataType.Date)]
        public DateTime InvoiceSubmissionDate { get; set; }
        public string Remarks { get; set; }

        [DisplayName("Inv. Number")]
        public string Cid { get; set; }
        [NotMapped]
        public decimal TotalAmount { get; set; }  // sum of unitprice and claim amount
        public bool IsPayment { get; set; }
        [DisplayName("Payment Recieve Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime? PaymentRecieveDate { get; set; }
        public string BankDetails { get; set; }
        public decimal RecieveAmount { get; set; }
    }
    public class InvoiceDetails : BaseModel
    {
        [DisplayName("PO.")]
        public Int64 PoFk { get; set; }
        public Int64 InvoiceMasterFk { get; set; }
        [NotMapped]
        [DisplayName("Payment Milestone")]
        public List<string> Milestones { get; set; }
        //public Int64 PaymentMilestoneFk { get; set; }
        [DisplayName("Site Name")]
        public Int64 SiteFk { get; set; }  // Po Details Id....
        [DisplayName("Projected Invoice Amount")]
        public decimal SiteAmount { get; set; }
        public decimal Tax { get; set; }
        public decimal Vat { get; set; }
        [DisplayName("Other Claim Amount")]
        public decimal OtherClaimAmount { get; set; }
        [DisplayName("Total Amount")]
        [NotMapped]
        public decimal TotalAmount { get; set; }
        [DisplayName("Final Amount")]
        public decimal FinalAmount { get; set; }
        public string Remarks { get; set; }
    }
    public class InvoiceMilestone:BaseModel
    {
        public Int64 InvoiceDetailsFk { get; set; }
        public Int64 PayementMilestoneFk { get; set; }
    }
}

ONSJobTracker/ONSJobTracker/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ONSJobTracker.CustomizedFunction;
using ONSJobTracker.Models;
using ONSJobTracker.ViewModels.Status;

namespace ONSJobTracker.Controllers
{
    [SessionCheck]
    public class StatusController : Controller
    {
        #region Report Engineer Work Status

        public async Task<ActionResult> ReportEngineerWorkStatusIndex(int? planid,int? siteid)

        {
            using (var db = new xOssContext())
            {
                string employeeId = EncryptDecrypt.Decrypt(System.Web.HttpContext.Current.Request.Cookies["UserInfo"]?["EmployeeId"]);
                ViewBag.project = new SelectList(DropDownListHelper.GetProjectsOfAssignedReportEngineer(Convert.ToInt32(employeeId)), "Value", "Text");
                
                ViewBag.workstatus = new SelectList(DropDownListHelper.GetWorkStatus(), "Value", "Text");
                ViewBag.reportstatus = new SelectList(DropDownListHelper.GetReportStatus(), "Value", "Text");

                ReportEngineerWorkStatusViewModel viewmodel = new ReportEngineerWorkStatusViewModel();
                ViewBag.reporteng = viewmodel.ListReportEngineer(Convert.ToInt32(employeeId));


                if (planid!=null)
                {
                    var plandetailsinfo = (from t1 in db.PlanningMaster
                                               //join t2 in db.PoDetails on t1.PoDetailsFk equals t2.Id
                                           join t2 in db.Planning on t1.Id equals t2.PlanningMasterFk
                                           join t5 in db.PoDetails on t2.PoDetailsFk equals t5.Id
                                           join t3 in db.PoMaster on t5.PoMasterFk equals t3.Id
                                           join t4 in db.Project on t3.ProjectFk equals t4.Id
                                           where t1.Id == planid && t2.PoDetailsFk == siteid
                                           select new
                                           {
                                               ProjectId = t4.Id,
                                               PoMasterId = t3.Id,
                                               PoDetailsId = t2.PoDetailsFk
                                           }).FirstOrDefault();
                    ReportEngineerWorkStatus model = new ReportEngineerWorkStatus
                    {
                        ProjectFk= plandetailsinfo.ProjectId,
                        DeliveredDate = DateTime.Now
                    };
                    ViewBag.DropdownId = new JavaScriptSerializer().Serialize(plandetailsinfo);
                    return await Task.Run(() => View(model));
                }
                else
                {
                    ReportEngineerWorkStatus model = new ReportEngineerWorkStatus
                    {
                        //CompletedDate = DateTime.Now,
                        DeliveredDate = DateTime.Now
                    };
                    return await Task.Run(() => View(model));
                }
       
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateReportEngineerWorkStatus(ReportEngineerWorkStatus model, HttpPostedFileBase logFile)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    string filename = "";
                    if (model.Action == "Save")
                    {
                        if (logFile != null && logFile.ContentLength > 0)
                        {
                            string fileExtension = Path.GetExtension(logFile.FileName)?.ToLower();

                            //logfile.FileName;
                            var character = FileLocation.GetRandomNumber();
                            filename = "R-" + model.SiteName + character.ToString() + "(" + DateTime.Now.ToString("d") + ")" + fileExtension;
                            //string fileLocation = Server.MapPath(FileLocation.LogFile) + filename;
                            string fileLocation = Server.MapPath(FileLocation.LogFile) + filename;
                            logFile.SaveAs(fileLocation);
                        }
                        model.ReportFile = filename;
                        model.AddReady(true, DateTime.Now);
                        db.ReportEngineerWorkStatus.Add(model);
                        await db.SaveChangesAsync();

                        //sweet alert
                        Session["success_div"] = "true";
                        Session["success_msg"] = "Insert Successfully.";

                    }
                    else if (model.Action == "Update")
                    {
                        {
                            ReportEngineerWorkStatus selectSingle =
                                 db.ReportEngineerWorkStatus.FirstOrDefault(x => x.Id == model.Id);
                            // to remove  same key already exists in the ObjectStateManager
                            ((IObjectContextAdapter)db).ObjectContext.Detach(selectSingle);
                            if (selectSingle != null)
                            {
                                if (logFile != null && logFile.ContentLength > 0)
                                {
                                    string fullPath = Request.MapPath(FileLocation.LogFile + selectSingle.ReportFile);
                                    if (System.IO.File.Exists(fullPath))
                                    {
                                        System.IO.File.Delete(fullPath);
                                    }
                                    string fileExtension = Path.GetExtension(logFile.FileName)?.ToLower();

                                    //logfile.FileName;
                                    var character = FileLocation.GetRandomNumber();
                                    filename = "R-" + model.SiteName + character.ToString() + "(" + DateTime.Now.ToString("d") + ")" + fileExtension;
                                    //string fileLocation = Server.MapPath(FileLocation.LogFile) + filename;
                                    string fileLocation = Server.MapPath(FileLocation.LogFile) + filename;
                                    logFile.SaveAs(fileLocation);
                                    model.ReportFile = filename;
                                }
                                else
                                {
                                    model.ReportFile = selectSingle.ReportFile;
                                }
                                model.PoFk = selectSingle.PoFk;
                                model.SiteFk = selectSingle.SiteFk;
                                model.PlanningMasterFk = selectSingle.PlanningMasterFk;
                                model.InsertBy = selectSingle.InsertBy;
                                model.InsertDate = selectSingle.InsertDate;

                                model.UpdateReady(true, DateTime.Now);
                                SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data),
                                    "ReportEngineerWorkStatus", "Update");
                                db.Entry(model).State = EntityState.Modified;
                                await db.SaveChangesAsync();
                                //sweet alert
                                Session["success_div"] = "true";
                                Session["success_msg"] = "Updated Successfully.";
                            }
                        }

                    }
                }
                return RedirectToAction("ReportEngineerWorkStatusIndex");
            }
            catch (Exception e)
            {

                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further problem, Contact with Concern People.";
            }
            return await Task.Run(() => View("ReportEngineerWorkStatusIndex"));
        }

        public async Task<ActionResult> DeleteReportEngineerWorkStatus(int id)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    ReportEngineerWorkStatus selectSingle = db.ReportEngineerWorkStatus.Find(id);
                    if (selectSingle != null)
                    {
                        db.ReportEngineerWorkStatus.Remove(selectSingle);
                        SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data),
                            "ReportEngineerWorkStatus", "Delete");
                        await db.SaveChangesAsync();
                        //sweet alert
                        Session["success_div"] = "true";
                        Session["success_msg"] = "Delete Successfully.";
                        return RedirectToAction("ReportEngineerWorkStatusIndex");
                    }
                }
            }
            catch (Exception e)
            {

                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further problem, Contact with Concern People.";
            }
            return RedirectToAction("ReportEngineerWorkStatusIndex");
        }

        public async Task<ActionResult> SubmitReportEngineerWorkStatus(int id)
        {
            try
            {
                var report = new ReportEngineerWorkStatus { Id = id, Status = false };
                using (var db = new xOssContext()) // use your DbConext
                {
                    db.ReportEngineerWorkStatus.Attach(report);

ONSJobTracker/ONSJobTracker/Views/Status/InvoiceMasterStatusIndex.cshtml
@using ONSJobTracker.ViewModels.Status
@model ONSJobTracker.Models.InvoiceMaster

@{
    ViewBag.Title = "InvoiceMasterStatusIndex";

    var tdsitefk = "tdsitefk";
    var tdcid = "tdcid";
    var tdpo = "tdpo";
    var tdinvoicefk = "tdinvoicefk"; //invoice status fk
    var tdinvoicesubdate = "tdinvoicesubdate"; //invoice submisstion date
    var tdinvoicepaydate = "tdinvoicepaydate"; //projected payment date
    var tdremarks = "tdremarks";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- form start -->
@using (Html.BeginForm("CreateInvoiceMasterStatus", "Status", FormMethod.Post, new { id = "invoicemasterstatus" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id, new { Value = "", id = "hidId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Invoice 
            <small>Status</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">InvoiceMasterStatusIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Invoice Master</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Cid)
                            @Html.TextBoxFor(model => model.Cid, new { id = "txtCid", placeholder = "Invoice Number", @readonly = "readonly", @class = "form-control", style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Cid, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.InvoiceStatusFk) &nbsp;<i class="ion-star"></i>
                            @Html.DropDownListFor(model => model.InvoiceStatusFk, ViewBag.invoicestatus as SelectList,
                                "---Select Invoice Status---", new {id = "ddlInvoiceStatusFk", @class = "form-control select2", style = "width:100%"})
                            @Html.ValidationMessageFor(model => model.InvoiceStatusFk, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.InvoiceSubmissionDate, new { @class = "control-label" })
                            &nbsp; <span><i class="ion-star  "></i></span>
                            <div class="input-group">
                                @Html.TextBoxFor(model => model.InvoiceSubmissionDate, "{0:yyyy/MM/dd}", new { id = "txtInvSubdate", @class = "form-control datepicker" })
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                            @Html.ValidationMessageFor(model => model.InvoiceSubmissionDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProjectedPaymentDate, new { @class = "control-label" })
                            &nbsp; <span><i class="ion-star  "></i></span>
                            <div class="input-group">
                                @Html.TextBoxFor(model => model.ProjectedPaymentDate, "{0:yyyy/MM/dd}", new { id = "txtProjPaydate", @class = "form-control datepicker" })
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                            @Html.ValidationMessageFor(model => model.ProjectedPaymentDate, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Remarks)
                            @Html.TextAreaFor(model => model.Remarks, new { id = "txtRemarks", placeholder = "Remarks", @class = "form-control", style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                        <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Invoices</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="tablewithsearch" class="table table-striped table-condensed table-bordered f11">
                            <thead>
                                <tr>
                                    <th class="hidden">Id</th>
                                    <th >#</th>

                                    <th class="hidden">Po fk</th>
                                    @*<th >PO.</th>*@
                                    <th >Inv. Number</th>

                                    <th class="hidden">IS id</th>
                                    <th >Inv. Status</th>

                                    <th >Inv. Sub. Date</th>
                                    <th>Proj. Payment Date</th>
                                    <th style="font-weight: bold">T. Amount</th>
                                    <th>Remarks</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    List<InvoiceMasterViewModel> invoicemaster = ViewBag.invoicemaster as List<InvoiceMasterViewModel>;
                                    int sl = 0;
                                    if (invoicemaster != null)
                                    {

                                        foreach (var ac in invoicemaster)
                                        {
                                            sl += 1;
                                            <tr>
                                                <td class="hidden">@ac.Id</td>
                                                <td style="text-align: right;">@sl</td>

                                                <td id="@tdsitefk@ac.Id" class="hidden">@ac.PoFk</td>
                                                @*<td>@ac.Po</td>*@
                                                <td id="@tdcid@ac.Id" style="text-align: left; ">@ac.Cid</td>
                                               
                                                <td id="@tdinvoicefk@ac.Id" class="hidden">@ac.InvoiceStatusFk</td>
                                                <td style="text-align: left;">@ac.InvoiceStatus</td>

                                                <td id="@tdinvoicesubdate@ac.Id" style="text-align: left; ">@ac.InvoiceSubmissionDate.ToShortDateString()</td>
                                                <td id="@tdinvoicepaydate@ac.Id" style="text-align: left;" >@ac.ProjectedPaymentDate.ToShortDateString()</td>
                                                <td style="text-align: right;font-weight: bold" >@ac.TotalAmount</td>

                                                <td id="@tdremarks@ac.Id" style="text-align: left;">@ac.Remarks</td>
                                                <td style="text-align: center;cursor: pointer">
                                                    <a id="@ac.Id" onclick=" invoiceinfo(this);" title="Edit"
                                                       data-placement="top">
                                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                    </a>
                                                    @*<a href="@Url.Action("DeleteInvoiceStatus", "Status", new RouteValueDictionary(new {id = ac.Id}))" id="@ac.Id" class="glyphicon glyphicon-trash no-print"
                                                       data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                       data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Acceptance Deleting"
                                                       data-swal-text="Are you sure to Delete this Acceptance Status?">
                                                    </a>*@
                                                    <a href="@Url.Action("InvoiceDetailsIndex", "Status", new RouteValueDictionary(new {id = ac.Id}))" id="@ac.Id" 
                                                       title="Detail" data-placement="top">
                                                        <i class="fa fa-binoculars" aria-hidden="true"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

@section ScriptFile {
    <script type="text/javascript">
        $(document).ready(function () {

            $.ajax({
                type: "POST",
                url: '@Url.Action("GenerateInvNumByPo", "Helper")',
                datatype: "Json",
                data: { poid: $("#ddlPoFk").val() },
                success: function (data) {
                    $('#txtCid').val(data.counter);
                }
            });

           // $('[data-datetimepicker-startdate]').datepicker({});


            $("#txtOtherClaimAmount/*, #2*/").change(function(){
                var val1 = parseFloat($("#txtProjectedInvoiceAmount").val()),
                    val2 = parseFloat($("#txtOtherClaimAmount").val());

                $("#txtInvoicedAmount").val(val1 + val2);
            });
        });
        function invoiceinfo(elem) {
            if (elem !== null) {
                var r = elem.id;
                $('#hidId').val(r);
                $('#hidAction').val('Update');
                $('#btnsave').html("<i class='fa fa-edit'></i>&nbsp;Update");

                //$('#ddlPoFk').val($('#tdsitefk' + r).text().trim()).trigger('change');
                $('#ddlPoFk').val($('#tdsitefk' + r).text().trim());
                $('#divPoFk').hide();
                //$('#txtPo').val($('#tdpo' + r).text().trim());
                $('#txtProjPaydate').val($('#tdinvoicepaydate' + r).text().trim());
                $('#txtInvSubdate').val($('#tdinvoicesubdate' + r).text().trim());
                $('#ddlInvoiceStatusFk').val($('#tdinvoicefk' + r).text().trim()).trigger('change');

                $('#txtRemarks').val($('#tdremarks' + r).text().trim());
                $('#txtCid').val($('#tdcid' + r).text().trim());

            }
        }
        $(document).off("click", "#btnreset");
        $(document).on("click", "#btnreset", function (e) {
            e.preventDefault();
            var act = $('#hidAction').val();
            if (act === "Update") {
                $('#hidAction').val("Save");
                $('#hidId').val('');
                $('#btnsave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");

                $('#ddlPoFk').val("").trigger('change');
                $('#divPoFk').show();
                //$('#txtPo').val($('#tdpo' + r).text().trim());
                $('#txtProjPaydate').val("");
                $('#txtInvSubdate').val("");
                $('#ddlInvoiceStatusFk').val("").trigger('change');
                $('#txtRemarks').val("");
                $('#txtCid').val("");

            } else {

            }
        });
        
        @*function invoiceNumber() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GenerateInvNumByPo", "Helper")',
                datatype: "Json",
                data: { poid: $("#ddlPoFk").val() },
                success: function (data) {
                    $('#txtCid').val(data.counter);
                }
            });
            //$("#ddlPoFk").change(function () {
                    
            //    });
        }*@
    </script>

}