ONSJobTracker/ONSJobTracker/ViewModels/Work Plan/WorkStatusView.cs
using ONSJobTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ONSJobTracker.ViewModels.Work_Plan;
using ONSJobTracker.ViewModels.Purchase_Order;
using ONSJobTracker.ViewModels.Status;

namespace ONSJobTracker.ViewModels.Work_Plan
{
    public class WorkStatusViewModel
    {
        public Int64 SiteId { get; set; }
        public string PlanmasterName { get; set; }
        public Int64 PlanningMasterId { get; set; }
        public string ProjectName { get; set; }
        public string PO { get; set; }
        public string SiteName { get; set; }
        public int WorkStatus { get; set; }
        public int ReportStatus { get; set; }
        public int TeamLeaderStatus { get; set; }
        public int Type { get; set; }
    }

    public class WorkStatusDetails {

        public List<ApprovalMaster> ApprovalMaster { get; set; }
        public List<PoDetailsViewModel> PoDetailsView { get; set; }
        public List<WorkUpdateViewModel> WorkUpdates { get; set; }
        public List<ReportEngineerWorkStatusViewModel> ReportStatus { get; set; }
    }

}

ONSJobTracker/ONSJobTracker/Controllers/PlanningController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ONSJobTracker.CustomizedFunction;
using ONSJobTracker.Models;
using ONSJobTracker.ViewModels.Purchase_Order;
using ONSJobTracker.ViewModels.Status;
using ONSJobTracker.ViewModels.Work_Plan;

namespace ONSJobTracker.Controllers
{
    [SessionCheck]
    public class PlanningController : Controller
    {
        private xOssContext _db = new xOssContext();
        // GET: Planning
        public async Task<ActionResult> WorkPlanIndex()
        {

            Planning model = new Planning
            {
                StartDate = DateTime.Today,
                FinishDate = DateTime.Today
            };
            ViewBag.allproject = new SelectList(DropDownListHelper.GetProjects(), "Value", "Text");
            ViewBag.allpomaster = new SelectList(DropDownListHelper.GetPoMaster(), "Value", "Text");
            ViewBag.allplanengineertype = new SelectList(DropDownListHelper.GetPlanEngineerType(), "Value", "Text");
            ViewBag.allresourcetype = new SelectList(DropDownListHelper.GetResourceType(), "Value", "Text");
            ViewBag.allfueltype = new SelectList(DropDownListHelper.GetfuelType(), "Value", "Text");
            ViewBag.allengineer = new SelectList(DropDownListHelper.GetEngineer(3), "Value", "Text"); //hard coded need to put engineer value manually
            return await Task.Run(() => View(model));
        }

        public async Task<ActionResult> CreateWorkPlan(FormCollection collection, List<string> SiteList)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    //var format = "dd-mm-yyyy"; // your datetime format
                    //var dateTimeConverter = new IsoDateTimeConverter { DateTimeFormat = format };

                    string plan = Request.Form["PlanList"];
                    string transportplan = Request.Form["TransportPlanList"];
                    string othercostplan = Request.Form["OtherCostPlanList"];
                    //int siteid = Convert.ToInt32(Request.Form["Site"]);



                    var data = JsonConvert.DeserializeObject<List<WorkPlanViewModel>>(plan);
                    var transportdata = JsonConvert.DeserializeObject<List<TransportViewModel>>(transportplan);
                    var othercostdata = JsonConvert.DeserializeObject<List<OtherCostViewModel>>(othercostplan);
                    //var delsiteid = data.FirstOrDefault();
                    //db.Planning.RemoveRange(db.Planning.Where(x => x.PoDetailsFk == delsiteid.PoDetailsFk));


                    WorkPlanViewModel a = new WorkPlanViewModel();
                    string planRef = a.GetPlanReference();

                    PlanningMaster master = new PlanningMaster
                    {
                        PoDetailsFk = 0,
                        PlanReference = planRef
                    };
                    master.AddReady(true, DateTime.Now);
                    db.PlanningMaster.Add(master);
                    db.SaveChanges();
                    Int64 masterid = master.Id;


                    //var a = data[PoDetailsFk];
                    if (data != null && data.Any())
                    {
                        foreach (var site in SiteList)
                        {
                            Planning model = new Planning();
                            foreach (var viewmodel in data)
                            {
                                decimal taamount = 0;
                                decimal daamount = 0;
                                //DateTime startdate = DateTime.ParseExact(viewmodel.StartDate, "M/d/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                                //DateTime finishdate = DateTime.ParseExact(viewmodel.StartDate, "M/d/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                                model.PlanningMasterFk = masterid;
                                model.PoDetailsFk = Convert.ToInt64(site);
                                model.EmployeeInfoFk = viewmodel.EmployeeInfoFk;
                                model.StartDate = viewmodel.StartDate;
                                model.FinishDate = viewmodel.FinishDate;
                                model.Ta = viewmodel.Ta;
                                model.Da = viewmodel.Da;
                                model.Ta = viewmodel.OutsideTa;
                                model.Da = viewmodel.OutsideDa;
                                if (viewmodel.Ta)
                                {
                                    taamount += a.GetTaAmountByEmployeeDesignation(viewmodel.EmployeeInfoFk);
                                }
                                if (viewmodel.OutsideTa)//Half Da
                                {
                                    daamount += a.GetOutsideTaAmountByEmployeeDesignation(viewmodel.EmployeeInfoFk);
                                }
                                if (viewmodel.Da)
                                {
                                    daamount += a.GetDaAmountByEmployeeDesignation(viewmodel.EmployeeInfoFk);
                                }
                                if (viewmodel.OutsideDa)
                                {
                                    daamount += a.GetOutsideDaAmountByEmployeeDesignation(viewmodel.EmployeeInfoFk);
                                }

                                TimeSpan difference = viewmodel.FinishDate - viewmodel.StartDate; //create TimeSpan object
                                int days = (int)Math.Ceiling(difference.TotalDays);
                                model.Duration = days + 1;
                                model.TaAmount = (taamount * model.Duration) / SiteList.Count;
                                model.DaAmount = (daamount * model.Duration) / SiteList.Count;
                                model.Type = viewmodel.Type;
                                model.Remarks = viewmodel.Remarks;
                                model.AddReady(true, DateTime.Now);
                                db.Planning.Add(model);
                                db.SaveChanges();

                                // NO Report
                                if (model.Type==2 && model.EmployeeInfoFk== 10039)
                                {
                                    var report = new ReportEngineerWorkStatus
                                    {
                                        PoFk = db.PoDetails.Where(x=>x.Id==model.PoDetailsFk).Select(x=>x.PoMasterFk).FirstOrDefault(),
                                        SiteFk = model.Id,
                                        WorkStatusFk = 5,
                                        ReportStatusFk = 5,
                                        DeliveredDate = DateTime.Now,
                                        InsertBy = model.InsertBy,
                                        InsertDate = DateTime.Now,
                                        Status = true,
                                        IsWorkReassign = false,
                                        IsReportReassign = false,
                                        IsDelivered = false,
                                        IsReadyForAcceptance = false,
                                        ReportWorkRef = 0,
                                        PlanningMasterFk = model.PlanningMasterFk
                                    };
                                    db.ReportEngineerWorkStatus.Add(report);
                                    await db.SaveChangesAsync();
                                }
                                
                            }
                        }

                    }

                    if (transportdata != null && transportdata.Any())
                    {
                        Transport transport = new Transport();
                        foreach (var transporviewtmodel in transportdata)
                        {
                            //DateTime tstartdate = DateTime.ParseExact(transporviewtmodel.StartDate, "M/d/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                            //DateTime tfinishdate = DateTime.ParseExact(transporviewtmodel.StartDate, "M/d/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                            transport.PlanningMasterFk = masterid;
                            transport.CarInfo = transporviewtmodel.CarInfo;
                            transport.DailyCost = transporviewtmodel.DailyCost;
                            transport.EstimatedDuration = transporviewtmodel.Duration;
                            transport.EstimatedKm = transporviewtmodel.EstimatedKm;
                            transport.FinishDate = transporviewtmodel.FinishDate;
                            transport.StartDate = transporviewtmodel.StartDate;
                            transport.FuelType = transporviewtmodel.FuelType;
                            transport.Remarks = transporviewtmodel.Remarks;
                            transport.TotalCarCost = transporviewtmodel.TotalCarCost;
                            transport.AddReady(true, DateTime.Now);
                            db.Transport.Add(transport);
                            await db.SaveChangesAsync();
                        }
                    }

                    if (othercostdata != null && othercostdata.Any())
                    {
                        OtherPlanCost cost = new OtherPlanCost();

ONSJobTracker/ONSJobTracker/Views/Planning/AcceptedPlanList.cshtml
@model IEnumerable<ONSJobTracker.Models.PlanningMaster>
@{
    ViewBag.Title = "WorkPlanListForApproval";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Plans
        <small>Setting</small>
    </h1>
    <ol class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">Accepted Plan List</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Accepted Work Plan List</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th class="hidden">ID</th>
                                        <th>#</th>
                                        <th style="text-align: center">Plan Reference</th>
                                        <th style="text-align: center">Status</th>
                                        @*<th style="text-align: center">Accounts Approval</th>*@
                                        <th style="text-align: center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (Model != null)
                                        {
                                            var sl = 1;
                                            foreach (var data in Model)
                                            {
                                                <tr>
                                                    <td class="hidden">@data.Id</td>
                                                    <td>@sl</td>
                                                    <td>@data.PlanReference</td>
                                                    <td class="text-center">
                                                        @if (data.AdminApproval)
                                                        {
                                                            <span class="label-success">Approved</span>
                                                        }
                                                        else
                                                        {
                                                            <span class="label-danger">Not Approved</span>
                                                        }
                                                    </td>
                                                    @*<td class="text-center">
                                                            @if (data.AccountsApproval)
                                                            {
                                                                <span class="label-success">Approved</span>
                                                            }
                                                            else
                                                            {
                                                                <span class="label-danger">Not Approved</span>
                                                            }
                                                        </td>*@
                                                    <td style="text-align: center; cursor: pointer; vertical-align: middle">
                                                        <a href="@Url.Action("AssignAmountForPlan", "Planning", new RouteValueDictionary(new {id = data.Id}))" id="@data.Id"
                                                           title="Detail" data-placement="top">
                                                            <i class="fa fa-user" aria-hidden="true"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                                sl += 1;
                                            }

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

ONSJobTracker/ONSJobTracker/Views/Planning/DailyWorkList.cshtml
@model IEnumerable<ONSJobTracker.ViewModels.Work_Plan.WorkUpdateViewModel>
@{
    ViewBag.Title = "WorkUpdateList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Work Updates
        <small>Setting</small>
    </h1>
    <ol class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active"> Work Updates List</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title"> Work Updates List</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th style="text-align: center">Date</th>
                                        <th style="text-align: center">Project Name</th>
                                        <th style="text-align: center">PO NO</th>
                                        <th style="text-align: center">Site Name</th>
                                        <th style="text-align: center">Start Time</th>
                                        <th style="text-align: center">End Time</th>
                                        <th style="text-align: center">Work Status</th>
                                        <th style="text-align: center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (Model != null)
                                        {
                                            foreach (var data in Model)
                                            {
                                                <tr>
                                                   
                                                   <td style="text-align: center">@data.Date.ToString("dd MMM yy")</td>
                                                   <td style="text-align: center">@data.Project</td>
                                                   <td style="text-align: center">@data.PoNo</td>
                                                   <td style="text-align: center">@data.Site</td>
                                                   <td style="text-align: center">@data.StartTime</td>
                                                    <td style="text-align: center">@data.EndTime</td>
                                                   
                                                
                                                    <td style="text-align: center">

                                                        @{
                                                            if (data.WorkStatusId == 1)
                                                            {
                                                                <span class="label label-default">@data.WorkStatus</span>
                                                            }
                                                            else if (data.WorkStatusId == 2)
                                                            {
                                                                <span class="label label-info">@data.WorkStatus</span>
                                                            }
                                                            else if (data.WorkStatusId == 5)
                                                            {
                                                                <span class="label label-warning">@data.WorkStatus</span>
                                                            }
                                                            else if (data.WorkStatusId == 7)
                                                            {
                                                                <span class="label label-danger">@data.WorkStatus</span>
                                                            }
                                                            else if (data.WorkStatusId == 6)
                                                            {
                                                                <span class="label label-success">@data.WorkStatus</span>
                                                            }
                                                        }

                                                    </td>
                                                
                                                
                                                    
                                                    <td style="text-align: center; cursor: pointer; vertical-align: middle">
                                                        <a href="@Url.Action("DailyWorkEngineerIndex", "Planning", new RouteValueDictionary(new {id = data.Id}))" id="@data.Id" 
                                                           title="Detail" data-placement="top">
                                                            <i class="fa fa-binoculars" aria-hidden="true"></i>
                                                        </a>
                                                        <a id="@data.Id" href="@Url.Action("UpdateDailyWork", "Planning", new RouteValueDictionary(new {workid = data.Id}))" title="Edit"
                                                           data-placement="top">
                                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                        </a>
                                                        <a href="@Url.Action("DeleteDailyWork", "Planning", new RouteValueDictionary(new {id = data.Id}))" id="@data.Id" class="glyphicon glyphicon-trash no-print"
                                                           data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                           data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Work Deleting"
                                                           data-swal-text="Are you sure to Delete this Work?">
                                                        </a>

                                                    </td>
                                                </tr>
                                                                }
                                                            }


                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

ONSJobTracker/ONSJobTracker/Views/Planning/TransportPlanEdit.cshtml
@model ONSJobTracker.Models.Transport
@{
    ViewBag.Title = "TransportPlanEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- form start -->
@using (Html.BeginForm("TransportPlanEdit", "Planning", FormMethod.Post, new { id = "frmTransportPlan" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.InsertBy)
    @Html.HiddenFor(model => model.InsertDate)
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Master Menu
            <small>Setting</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">TransportPlanIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add Transport Plan</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-4"> </div>
                        <div class="col-md-4">

                            <div class="form-group">
                                @Html.LabelFor(model => model.PlanningMasterFk) &nbsp;<i class="ion-star"></i>
                                @Html.DropDownListFor(model => model.PlanningMasterFk, ViewBag.allplan as SelectList,
                                    "---Select Plan---", new { id = "ddlPlanningMasterFk", @class = "form-control select2", style = "width:100%" })
                                @Html.ValidationMessageFor(model => model.PlanningMasterFk, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.TransportCid) &nbsp;<i class="ion-star"></i>
                                @Html.TextBoxFor(model => model.TransportCid, new { id = "txtTransportCid", placeholder = "Transport Reference", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TransportCid, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EstimatedDuration) &nbsp;<i class="ion-star"></i>
                                @Html.TextBoxFor(model => model.EstimatedDuration, new { Value = 0, id = "txtEstimatedDuration", placeholder = "Transport Reference", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.EstimatedDuration, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.CarInfo) &nbsp;<i class="ion-star"></i>
                                @Html.DropDownListFor(model => model.CarInfo, ViewBag.allcartype as SelectList,
                                    "---Select Car Type---", new { id = "ddlCarInfo", @class = "form-control select2", style = "width:100%" })
                                @Html.ValidationMessageFor(model => model.CarInfo, "", new { @class = "text-danger" })
                            </div>
                            <div id="divOwnCar" style="display: none">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FuelType) &nbsp;<i class="ion-star"></i>
                                    @Html.DropDownListFor(model => model.FuelType, ViewBag.allfueltype as SelectList,
                                        "---Select Fuel Type---", new { id = "ddlFuelType", @class = "form-control select2", style = "width:100%" })
                                    @Html.ValidationMessageFor(model => model.FuelType, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.EstimatedKm) &nbsp;<i class="ion-star"></i>
                                    @Html.TextBoxFor(model => model.EstimatedKm, new { Value = 0, id = "txtEstimatedKm", placeholder = "Transport Reference", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EstimatedKm, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TotalCarCost) &nbsp;<i class="ion-star"></i>
                                @Html.TextBoxFor(model => model.TotalCarCost, new { Value = 0, id = "txtTotalCarCost", placeholder = "Transport Reference", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TotalCarCost, "", new { @class = "text-danger" })
                            </div>
                            <div class="box-footer">
                                <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                                <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                            </div>
                        </div>
                        <div class="col-md-4"> </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
}


@section ScriptFile
{
    <script type="text/javascript">
        $('#ddlCarInfo').on("change",
            function (e) {
              var a=  $('#ddlCarInfo').val();
                if (a === "1") {
                    $("#divOwnCar").show();
                } else {
                    $("#divOwnCar").hide();
                }

            });
        $("#ddlCarInfo").trigger("change");
    </script>
}