ONSJobTracker/ONSJobTracker/Controllers/UserAccessController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using ONSJobTracker.CustomizedFunction;
using ONSJobTracker.Models;
using ONSJobTracker.ViewModels.UserEmployee;

namespace ONSJobTracker.Controllers
{
    [SessionCheck]
    public class UserAccessController : Controller
    {
        private xOssContext _db = new xOssContext();
        #region Employee Designation

        public async Task<ActionResult> EmployeeDesignationIndex()
        {
            using (var db = new xOssContext())
            {
                ViewBag.alldesignation = db.EmployeeDesignation.OrderBy(x => x.Id).ToList();
                return await Task.Run(() => View());
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateEmployeeDesignation(EmployeeDesignation model)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    if (model.Action == "Save")
                    {
                        if (db.EmployeeDesignation.Any(o => o.Name.ToLower() == model.Name.ToLower()))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Employee Designation exists.";
                            return RedirectToAction("EmployeeDesignationIndex");
                        }
                        else
                        {
                            model.AddReady(true, DateTime.Now);
                            db.EmployeeDesignation.Add(model);
                            await db.SaveChangesAsync();

                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Inserst Successfully.";
                        }
                    }
                    else if (model.Action == "Update")
                    {
                        if (db.EmployeeDesignation.Any(x => x.Name == model.Name && x.Id != model.Id))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Employee Designation exists.";
                        }
                        else
                        {
                            EmployeeDesignation selectSingle = db.EmployeeDesignation.FirstOrDefault(x => x.Id == model.Id);
                            // to remove  same key already exists in the ObjectStateManager
                            ((IObjectContextAdapter)db).ObjectContext.Detach(selectSingle);
                            if (selectSingle != null)
                            {

                                model.InsertBy = selectSingle.InsertBy;
                                model.InsertDate = selectSingle.InsertDate;

                                model.UpdateReady(true, DateTime.Now);
                                SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data),
                                    "EmployeeDesignation", "Update");
                                db.Entry(model).State = EntityState.Modified;
                                await db.SaveChangesAsync();
                                //sweet alert
                                Session["success_div"] = "true";
                                Session["success_msg"] = "Updated Successfully.";
                            }
                        }

                    }
                }
                return RedirectToAction("EmployeeDesignationIndex");
            }
            catch (Exception e)
            {
                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return await Task.Run(() => View("EmployeeDesignationIndex"));
        }

        public async Task<ActionResult> DeleteEmployeeDesignation(int id)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    EmployeeDesignation selectSingle = db.EmployeeDesignation.Find(id);
                    if (selectSingle != null)
                    {
                        db.EmployeeDesignation.Remove(selectSingle);
                        SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "EmployeeDesignation", "Delete");
                        await db.SaveChangesAsync();
                        //sweet alert
                        Session["success_div"] = "true";
                        Session["success_msg"] = "Delete Successfully.";
                        return RedirectToAction("EmployeeDesignationIndex");
                    }
                }
            }
            catch (Exception e)
            {
                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return RedirectToAction("EmployeeDesignationIndex");
        }

        #endregion

        #region Employee Department

        public async Task<ActionResult> EmployeeDepartmentIndex()
        {
            using (var db = new xOssContext())
            {
                ViewBag.alldepartment = db.EmployeeDepartment.OrderBy(x => x.Id).ToList();
                return await Task.Run(() => View());
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateEmployeeDepartment(EmployeeDepartment model)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    if (model.Action == "Save")
                    {
                        if (db.EmployeeDepartment.Any(o => o.Name.ToLower() == model.Name.ToLower()))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Employee Designation exists.";
                            return RedirectToAction("CreateEmployeeDesignation");
                        }
                        else
                        {
                            model.AddReady(true, DateTime.Now);
                            db.EmployeeDepartment.Add(model);
                            await db.SaveChangesAsync();

                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Inserst Successfully.";
                        }
                    }
                    else if (model.Action == "Update")
                    {
                        if (db.EmployeeDepartment.Any(x => x.Name == model.Name && x.Id != model.Id))
                        {
                            //sweet alert
                            Session["success_div"] = "true";
                            Session["success_msg"] = "Employee Designation exists.";
                        }
                        else
                        {
                            EmployeeDepartment selectSingle =
                                 db.EmployeeDepartment.FirstOrDefault(x => x.Id == model.Id);
                            // to remove  same key already exists in the ObjectStateManager
                            ((IObjectContextAdapter)db).ObjectContext.Detach(selectSingle);
                            if (selectSingle != null)
                            {

                                model.InsertBy = selectSingle.InsertBy;
                                model.InsertDate = selectSingle.InsertDate;

                                model.UpdateReady(true, DateTime.Now);
                                SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data),
                                    "EmployeeDepartment", "Update");
                                db.Entry(model).State = EntityState.Modified;
                                await db.SaveChangesAsync();
                                //sweet alert
                                Session["success_div"] = "true";
                                Session["success_msg"] = "Updated Successfully.";
                            }
                        }

                    }
                }
                return RedirectToAction("EmployeeDepartmentIndex");
            }
            catch (Exception e)
            {
                //sweet alert
                Session["warning_div"] = "true";
                Session["warning_msg"] = "Oops! Please, try again. For further probolem, Contact with Concern People.";
            }
            return await Task.Run(() => View("EmployeeDepartmentIndex"));
        }

        public async Task<ActionResult> DeleteEmployeeDepartment(int id)
        {
            try
            {
                using (var db = new xOssContext()) // use your DbConext
                {
                    EmployeeDepartment selectSingle = db.EmployeeDepartment.Find(id);
                    if (selectSingle != null)
                    {
                        db.EmployeeDepartment.Remove(selectSingle);
                        SaveLog.Save(db, new JavaScriptSerializer().Serialize(Json(selectSingle).Data), "EmployeeDesignation", "Delete");
                        await db.SaveChangesAsync();
                        //sweet alert
                        Session["success_div"] = "true";

ONSJobTracker/ONSJobTracker/Views/UserAccess/EmployeeDepartmentIndex.cshtml
@using ONSJobTracker.Models
@model EmployeeDepartment
@{
    ViewBag.Title = "Department";
    var tdname = "tdname";
    var tdremarks = "tdremarks";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- form start -->
@using (Html.BeginForm("CreateEmployeeDepartment", "UserAccess", FormMethod.Post, new { id = "employeedepartment" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id, new { Value = "", id = "hidId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Employee Department
            <small>Setting</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">EmployeeDepartmentIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Employee Department</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name) &nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.Name, new { id = "txtName", placeholder = "Department", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Remarks)
                            @Html.TextAreaFor(model => model.Remarks, new { id = "txtRemarks", placeholder = "Remarks", @class = "form-control", style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                        <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Employee Department</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden">Id</th>
                                    <th style="width: 10%">#</th>
                                    <th style="width: 30%">Name</th>
                                    <th style="width: 50%">Remarks</th>
                                    <th style="width: 10%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    List<EmployeeDepartment> departments = ViewBag.alldepartment as List<EmployeeDepartment>;
                                    int sl = 0;
                                    if (departments != null)
                                    {

                                        foreach (var department in departments)
                                        {
                                            sl += 1;
                                            <tr>
                                                <td class="hidden">@department.Id</td>
                                                <td>@sl</td>
                                                <td id="@tdname@department.Id">@department.Name</td>
                                                <td id="@tdremarks@department.Id">@department.Remarks</td>
                                                <td style="text-align: center;cursor: pointer">
                                                    <a id="@department.Id" onclick=" departmentinfo(this);" title="Edit"
                                                       data-placement="top">
                                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                    </a>
                                                    <a href="@Url.Action("DeleteEmployeeDepartment", "UserAccess", new RouteValueDictionary(new {id = department.Id}))" id="@department.Id" class="glyphicon glyphicon-trash no-print"
                                                       data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                       data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Employee Department Deleting"
                                                       data-swal-text="Are you sure to Delete this Employee Department?">
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
                                    }

@section ScriptFile {
    <script type="text/javascript">
        function departmentinfo(elem) {
            if (elem !== null) {
                var r = elem.id;
                $('#hidId').val(r);
                $('#hidAction').val('Update');
                $('#btnsave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#txtName').val($('#tdname' + r).text().trim());
                $('#txtRemarks').val($('#tdremarks' + r).text().trim());

            }
        }
        $(document).off("click", "#btnreset");
        $(document).on("click", "#btnreset", function (e) {
            e.preventDefault();
            var act = $('#hidAction').val();
            if (act === "Update") {
                $('#hidAction').val("Save");
                $('#hidId').val('');
                $('#btnsave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");
                $('#txtName').val("");
                $('#txtRemarks').val("");
            } else {

            }
        });
    </script>

}

ONSJobTracker/ONSJobTracker/Views/UserAccess/EmployeeDesignationIndex.cshtml
@using ONSJobTracker.Models
@model EmployeeDesignation
@{
    ViewBag.Title = "Designation";
    var tdname = "tdname";
    var tdta = "tdta";
    var tdda = "tdda";
    var tdoda = "tdoda";
    var tdota = "tdota";
    var tdremarks = "tdremarks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- form start -->
@using (Html.BeginForm("CreateEmployeeDesignation", "UserAccess", FormMethod.Post, new { id = "employeedesignation" }))
{
    @Html.HiddenFor(model => model.Action, new { Value = "Save", id = "hidAction" })
    @Html.HiddenFor(model => model.Id, new { Value = "", id = "hidId" })
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Employee Designation
            <small>Setting</small>
        </h1>
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">EmployeeDesignationIndex</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Employee Designation</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name) &nbsp;<i class="ion-star"></i>
                            @Html.TextBoxFor(model => model.Name, new { id = "txtName", placeholder = "Designation", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
               
                        <div class="box box-default">
                            <div class="box-header with-border">
                                <h3 class="box-title">Inside Dhaka TA/DA</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Ta) &nbsp;<i class="ion-star"></i>
                                    @Html.TextBoxFor(model => model.Ta, new { id = "txtTa", placeholder = "Travel Allowance", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Ta, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Da)&nbsp;<i class="ion-star"></i>
                                    @Html.TextBoxFor(model => model.Da, new {id = "txtDa", placeholder = "Dinning Allowance", @class = "form-control"})
                                    @Html.ValidationMessageFor(model => model.Da, "", new {@class = "text-danger"})
                                </div>

                            </div>
                        </div>
                        <div class="box box-default">
                            <div class="box-header with-border">
                                <h3 class="box-title">Outside Dhaka TA/DA</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OutsideTa) &nbsp;<i class="ion-star"></i>
                                    @Html.TextBoxFor(model => model.OutsideTa, new { id = "txtOutsideTa", placeholder = "Outside Travel Allowance", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.OutsideTa, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OutsideDa)&nbsp;<i class="ion-star"></i>
                                    @Html.TextBoxFor(model => model.OutsideDa, new { id = "txtOutsideDa", placeholder = "Outside Dinning Allowance", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.OutsideDa, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                     
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.Remarks)
                            @Html.TextAreaFor(model => model.Remarks, new { id = "txtRemarks", placeholder = "Remarks", @class = "form-control", style = "width:100%;" })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" id="btnsave" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;Save</button>&nbsp;&nbsp;&nbsp;
                        <button id='btnreset' type='button' class="btn btn-success"><i class='fa fa-recycle'></i>&nbsp;&nbsp;Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Employee Designation</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden">Id</th>
                                    <th style="width: 10%">#</th>
                                    <th style="width: 20%">Name</th>
                                    <th style="width: 10%">Inside Ta</th>
                                    <th style="width: 10%">Inside Da</th>
                                    <th style="width: 10%">Outside Ta</th>
                                    <th style="width: 10%">Outside Da</th>
                                    <th style="width: 20%">Remarks</th>
                                    <th style="width: 10%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    List<EmployeeDesignation> designations = ViewBag.alldesignation as List<EmployeeDesignation>;
                                    int sl = 0;
                                    if (designations != null)
                                    {

                                        foreach (var designation in designations)
                                        {
                                            sl += 1;
                                            <tr>
                                                <td class="hidden">@designation.Id</td>
                                                <td>@sl</td>
                                                <td id="@tdname@designation.Id">@designation.Name</td>
                                                <td id="@tdta@designation.Id">@designation.Ta</td>
                                                <td id="@tdda@designation.Id">@designation.Da</td>
                                                <td id="@tdota@designation.Id">@designation.OutsideTa</td>
                                                <td id="@tdoda@designation.Id">@designation.OutsideDa</td>
                                                <td id="@tdremarks@designation.Id">@designation.Remarks</td>
                                                <td style="text-align: center;cursor: pointer">
                                                    <a id="@designation.Id" onclick=" designationinfo(this);" title="Edit"
                                                       data-placement="top">
                                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                    </a>
                                                    <a href="@Url.Action("DeleteEmployeeDesignation", "UserAccess", new RouteValueDictionary(new {id = designation.Id}))" id="@designation.Id" class="glyphicon glyphicon-trash no-print"
                                                       data-tooltip="tooltip" title="Delete" data-placement="top" data-delconfirm="true"
                                                       data-swal-confirm-button-text="Yes, delete it!" data-swal-title="Employee Designation Deleting"
                                                       data-swal-text="Are you sure to Delete this Employee Designation?">
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
                                    }

@section ScriptFile {
    <script type="text/javascript">
        function designationinfo(elem) {
            if (elem !== null) {
                var r = elem.id;
                $('#hidId').val(r);
                $('#hidAction').val('Update');
                $('#btnsave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#txtName').val($('#tdname' + r).text().trim());
                $('#txtTa').val($('#tdta' + r).text().trim());
                $('#txtDa').val($('#tdda' + r).text().trim());
                $('#txtOutsideTa').val($('#tdota' + r).text().trim());
                $('#txtOutsideDa').val($('#tdoda' + r).text().trim());
                $('#txtRemarks').val($('#tdremarks' + r).text().trim());

            }
        }
        $(document).off("click", "#btnreset");
        $(document).on("click", "#btnreset", function (e) {
            e.preventDefault();
            var act = $('#hidAction').val();
            if (act === "Update") {
                $('#hidAction').val("Save");
                $('#hidId').val('');
                $('#btnsave').html("<i class='fa fa-floppy-o'></i>&nbsp;Save");
                $('#txtName').val("");
                $('#txtTa').val("");
                $('#txtDa').val("");
                $('#txtRemarks').val("");
            }
        });
    </script>

}